version: "3.9"
services:
  database:
    image: "postgres:15"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=bank_db
    volumes:
      - ./db_entry/:/docker-entrypoint-initdb.d
    ports:
    - "5432:5432"