version: "3.9"
services:
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=bank_db
    ports:
    - "5432:5432"